TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

#DIRS += iocs

# Install databases, templates & substitutions like this
DB += ModeBsaVersion.db
DB += beamPathDetermination.db

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

#TOP=../..
#include $(TOP)/configure/CONFIG
#DIRS += common
#DIRS += iocs
include $(TOP)/configure/RULES_DIRS

